// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dustMeasurement.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DustSensorMeasurement struct {
	ParticularMatter2_5Um *float32 `protobuf:"fixed32,1,req,name=particularMatter2_5um,json=particularMatter25um" json:"particularMatter2_5um,omitempty"`
	ParticularMatter10Um  *float32 `protobuf:"fixed32,2,req,name=particularMatter10um" json:"particularMatter10um,omitempty"`
	Temperature           *float32 `protobuf:"fixed32,3,req,name=temperature" json:"temperature,omitempty"`
	Humidity              *float32 `protobuf:"fixed32,4,req,name=humidity" json:"humidity,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *DustSensorMeasurement) Reset()         { *m = DustSensorMeasurement{} }
func (m *DustSensorMeasurement) String() string { return proto.CompactTextString(m) }
func (*DustSensorMeasurement) ProtoMessage()    {}
func (*DustSensorMeasurement) Descriptor() ([]byte, []int) {
	return fileDescriptor_dustMeasurement_7851260c5bed37d2, []int{0}
}
func (m *DustSensorMeasurement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DustSensorMeasurement.Unmarshal(m, b)
}
func (m *DustSensorMeasurement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DustSensorMeasurement.Marshal(b, m, deterministic)
}
func (dst *DustSensorMeasurement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DustSensorMeasurement.Merge(dst, src)
}
func (m *DustSensorMeasurement) XXX_Size() int {
	return xxx_messageInfo_DustSensorMeasurement.Size(m)
}
func (m *DustSensorMeasurement) XXX_DiscardUnknown() {
	xxx_messageInfo_DustSensorMeasurement.DiscardUnknown(m)
}

var xxx_messageInfo_DustSensorMeasurement proto.InternalMessageInfo

func (m *DustSensorMeasurement) GetParticularMatter2_5Um() float32 {
	if m != nil && m.ParticularMatter2_5Um != nil {
		return *m.ParticularMatter2_5Um
	}
	return 0
}

func (m *DustSensorMeasurement) GetParticularMatter10Um() float32 {
	if m != nil && m.ParticularMatter10Um != nil {
		return *m.ParticularMatter10Um
	}
	return 0
}

func (m *DustSensorMeasurement) GetTemperature() float32 {
	if m != nil && m.Temperature != nil {
		return *m.Temperature
	}
	return 0
}

func (m *DustSensorMeasurement) GetHumidity() float32 {
	if m != nil && m.Humidity != nil {
		return *m.Humidity
	}
	return 0
}

func init() {
	proto.RegisterType((*DustSensorMeasurement)(nil), "protobuf.dustSensorMeasurement")
}

func init() {
	proto.RegisterFile("dustMeasurement.proto", fileDescriptor_dustMeasurement_7851260c5bed37d2)
}

var fileDescriptor_dustMeasurement_7851260c5bed37d2 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x29, 0x2d, 0x2e,
	0xf1, 0x4d, 0x4d, 0x2c, 0x2e, 0x2d, 0x4a, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0xfb, 0x18, 0x21, 0x6a, 0x82, 0x53, 0xf3,
	0x8a, 0xf3, 0x8b, 0x90, 0x54, 0x0a, 0x19, 0x73, 0x89, 0x16, 0x24, 0x16, 0x95, 0x64, 0x26, 0x97,
	0xe6, 0x24, 0x16, 0xf9, 0x26, 0x96, 0x94, 0xa4, 0x16, 0x19, 0xc5, 0x9b, 0x96, 0xe6, 0x4a, 0x30,
	0x2a, 0x30, 0x69, 0x30, 0x05, 0x89, 0x60, 0x48, 0x9a, 0x96, 0xe6, 0x0a, 0x19, 0x71, 0x61, 0x88,
	0x1b, 0x1a, 0x94, 0xe6, 0x4a, 0x30, 0x61, 0xd7, 0x03, 0x92, 0x13, 0x52, 0xe0, 0xe2, 0x2e, 0x49,
	0xcd, 0x2d, 0x48, 0x2d, 0x4a, 0x2c, 0x29, 0x2d, 0x4a, 0x95, 0x60, 0x06, 0x2b, 0x45, 0x16, 0x12,
	0x92, 0xe2, 0xe2, 0xc8, 0x28, 0xcd, 0xcd, 0x4c, 0xc9, 0x2c, 0xa9, 0x94, 0x60, 0x01, 0x4b, 0xc3,
	0xf9, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x3b, 0x7f, 0x3b, 0xe2, 0x00, 0x00, 0x00,
}
