// Code generated by protoc-gen-go. DO NOT EDIT.
// source: applicationInformation.proto

package applicationInformation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestSoftwareInformation_InformationType int32

const (
	RequestSoftwareInformation_FIRMWARE_VERSION RequestSoftwareInformation_InformationType = 1
)

var RequestSoftwareInformation_InformationType_name = map[int32]string{
	1: "FIRMWARE_VERSION",
}
var RequestSoftwareInformation_InformationType_value = map[string]int32{
	"FIRMWARE_VERSION": 1,
}

func (x RequestSoftwareInformation_InformationType) Enum() *RequestSoftwareInformation_InformationType {
	p := new(RequestSoftwareInformation_InformationType)
	*p = x
	return p
}
func (x RequestSoftwareInformation_InformationType) String() string {
	return proto.EnumName(RequestSoftwareInformation_InformationType_name, int32(x))
}
func (x *RequestSoftwareInformation_InformationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestSoftwareInformation_InformationType_value, data, "RequestSoftwareInformation_InformationType")
	if err != nil {
		return err
	}
	*x = RequestSoftwareInformation_InformationType(value)
	return nil
}
func (RequestSoftwareInformation_InformationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_applicationInformation_94ed2c4db073841f, []int{0, 0}
}

type RequestSoftwareInformation struct {
	Information          *RequestSoftwareInformation_InformationType `protobuf:"varint,1,req,name=information,enum=RequestSoftwareInformation_InformationType,def=1" json:"information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *RequestSoftwareInformation) Reset()         { *m = RequestSoftwareInformation{} }
func (m *RequestSoftwareInformation) String() string { return proto.CompactTextString(m) }
func (*RequestSoftwareInformation) ProtoMessage()    {}
func (*RequestSoftwareInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_applicationInformation_94ed2c4db073841f, []int{0}
}
func (m *RequestSoftwareInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSoftwareInformation.Unmarshal(m, b)
}
func (m *RequestSoftwareInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSoftwareInformation.Marshal(b, m, deterministic)
}
func (dst *RequestSoftwareInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSoftwareInformation.Merge(dst, src)
}
func (m *RequestSoftwareInformation) XXX_Size() int {
	return xxx_messageInfo_RequestSoftwareInformation.Size(m)
}
func (m *RequestSoftwareInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSoftwareInformation.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSoftwareInformation proto.InternalMessageInfo

const Default_RequestSoftwareInformation_Information RequestSoftwareInformation_InformationType = RequestSoftwareInformation_FIRMWARE_VERSION

func (m *RequestSoftwareInformation) GetInformation() RequestSoftwareInformation_InformationType {
	if m != nil && m.Information != nil {
		return *m.Information
	}
	return Default_RequestSoftwareInformation_Information
}

type FirmwareVersion struct {
	Major                *uint32  `protobuf:"varint,1,req,name=major" json:"major,omitempty"`
	Minor                *uint32  `protobuf:"varint,2,req,name=minor" json:"minor,omitempty"`
	Patch                *uint32  `protobuf:"varint,3,req,name=patch" json:"patch,omitempty"`
	Hotfix               *uint32  `protobuf:"varint,4,req,name=hotfix" json:"hotfix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirmwareVersion) Reset()         { *m = FirmwareVersion{} }
func (m *FirmwareVersion) String() string { return proto.CompactTextString(m) }
func (*FirmwareVersion) ProtoMessage()    {}
func (*FirmwareVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_applicationInformation_94ed2c4db073841f, []int{1}
}
func (m *FirmwareVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirmwareVersion.Unmarshal(m, b)
}
func (m *FirmwareVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirmwareVersion.Marshal(b, m, deterministic)
}
func (dst *FirmwareVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirmwareVersion.Merge(dst, src)
}
func (m *FirmwareVersion) XXX_Size() int {
	return xxx_messageInfo_FirmwareVersion.Size(m)
}
func (m *FirmwareVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_FirmwareVersion.DiscardUnknown(m)
}

var xxx_messageInfo_FirmwareVersion proto.InternalMessageInfo

func (m *FirmwareVersion) GetMajor() uint32 {
	if m != nil && m.Major != nil {
		return *m.Major
	}
	return 0
}

func (m *FirmwareVersion) GetMinor() uint32 {
	if m != nil && m.Minor != nil {
		return *m.Minor
	}
	return 0
}

func (m *FirmwareVersion) GetPatch() uint32 {
	if m != nil && m.Patch != nil {
		return *m.Patch
	}
	return 0
}

func (m *FirmwareVersion) GetHotfix() uint32 {
	if m != nil && m.Hotfix != nil {
		return *m.Hotfix
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestSoftwareInformation)(nil), "requestSoftwareInformation")
	proto.RegisterType((*FirmwareVersion)(nil), "firmwareVersion")
	proto.RegisterEnum("RequestSoftwareInformation_InformationType", RequestSoftwareInformation_InformationType_name, RequestSoftwareInformation_InformationType_value)
}

func init() {
	proto.RegisterFile("applicationInformation.proto", fileDescriptor_applicationInformation_94ed2c4db073841f)
}

var fileDescriptor_applicationInformation_94ed2c4db073841f = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x2c, 0x28, 0xc8,
	0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xf3, 0xcc, 0x4b, 0xcb, 0x2f, 0xca, 0x05, 0x33, 0xf5,
	0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x95, 0x96, 0x31, 0x72, 0x49, 0x15, 0xa5, 0x16, 0x96, 0xa6, 0x16,
	0x97, 0x04, 0xe7, 0xa7, 0x95, 0x94, 0x27, 0x16, 0xa5, 0x22, 0x29, 0x12, 0x8a, 0xe7, 0xe2, 0xce,
	0x44, 0x70, 0x25, 0x18, 0x15, 0x98, 0x34, 0xf8, 0x8c, 0xb4, 0xf5, 0x70, 0xeb, 0xd0, 0x43, 0x62,
	0x87, 0x54, 0x16, 0xa4, 0x5a, 0x09, 0xb8, 0x79, 0x06, 0xf9, 0x86, 0x3b, 0x06, 0xb9, 0xc6, 0x87,
	0xb9, 0x06, 0x05, 0x7b, 0xfa, 0xfb, 0x05, 0x21, 0x9b, 0xa8, 0xa4, 0xce, 0xc5, 0x8f, 0xa6, 0x43,
	0x48, 0x84, 0x0b, 0x43, 0x8f, 0x00, 0xa3, 0x52, 0x36, 0x17, 0x7f, 0x5a, 0x66, 0x51, 0x2e, 0xc8,
	0xba, 0xb0, 0xd4, 0xa2, 0x62, 0x90, 0xe3, 0x44, 0xb8, 0x58, 0x73, 0x13, 0xb3, 0xf2, 0x8b, 0xc0,
	0xce, 0xe2, 0x0d, 0x82, 0x70, 0xc0, 0xa2, 0x99, 0x79, 0xf9, 0x45, 0x12, 0x4c, 0x50, 0x51, 0x10,
	0x07, 0x24, 0x5a, 0x90, 0x58, 0x92, 0x9c, 0x21, 0xc1, 0x0c, 0x11, 0x05, 0x73, 0x84, 0xc4, 0xb8,
	0xd8, 0x32, 0xf2, 0x4b, 0xd2, 0x32, 0x2b, 0x24, 0x58, 0xc0, 0xc2, 0x50, 0x1e, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x7b, 0xf4, 0x4c, 0x1e, 0x34, 0x01, 0x00, 0x00,
}
