// Code generated by protoc-gen-go. DO NOT EDIT.
// source: batteryState.proto

package batteryState

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BatteryState struct {
	Voltage              *float32 `protobuf:"fixed32,1,req,name=voltage" json:"voltage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatteryState) Reset()         { *m = BatteryState{} }
func (m *BatteryState) String() string { return proto.CompactTextString(m) }
func (*BatteryState) ProtoMessage()    {}
func (*BatteryState) Descriptor() ([]byte, []int) {
	return fileDescriptor_batteryState_30a17f4aeca15170, []int{0}
}
func (m *BatteryState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatteryState.Unmarshal(m, b)
}
func (m *BatteryState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatteryState.Marshal(b, m, deterministic)
}
func (dst *BatteryState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatteryState.Merge(dst, src)
}
func (m *BatteryState) XXX_Size() int {
	return xxx_messageInfo_BatteryState.Size(m)
}
func (m *BatteryState) XXX_DiscardUnknown() {
	xxx_messageInfo_BatteryState.DiscardUnknown(m)
}

var xxx_messageInfo_BatteryState proto.InternalMessageInfo

func (m *BatteryState) GetVoltage() float32 {
	if m != nil && m.Voltage != nil {
		return *m.Voltage
	}
	return 0
}

func init() {
	proto.RegisterType((*BatteryState)(nil), "batteryState")
}

func init() { proto.RegisterFile("batteryState.proto", fileDescriptor_batteryState_30a17f4aeca15170) }

var fileDescriptor_batteryState_30a17f4aeca15170 = []byte{
	// 70 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x4a, 0x2c, 0x29,
	0x49, 0x2d, 0xaa, 0x0c, 0x2e, 0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2,
	0xe0, 0xe2, 0x41, 0x16, 0x15, 0x92, 0xe0, 0x62, 0x2f, 0xcb, 0xcf, 0x29, 0x49, 0x4c, 0x4f, 0x95,
	0x60, 0x54, 0x60, 0xd2, 0x60, 0x0a, 0x82, 0x71, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x20,
	0x70, 0xb3, 0x3e, 0x00, 0x00, 0x00,
}
