/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Wed Aug 22 08:54:06 2018. */

#include "applicationInformation.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const protobuf_requestSoftwareInformation_RequestInformationType protobuf_requestSoftwareInformation_information_default = protobuf_requestSoftwareInformation_RequestInformationType_FIRMWARE_VERSION;


const pb_field_t protobuf_requestSoftwareInformation_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, protobuf_requestSoftwareInformation, information, information, &protobuf_requestSoftwareInformation_information_default),
    PB_LAST_FIELD
};

const pb_field_t protobuf_firmwareVersion_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, protobuf_firmwareVersion, major, major, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, protobuf_firmwareVersion, minor, major, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, protobuf_firmwareVersion, patch, minor, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, protobuf_firmwareVersion, hotfix, patch, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
