/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Sun Aug  5 17:39:22 2018. */

#include "applicationInformation.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const requestSoftwareInformation_InformationType requestSoftwareInformation_information_default = requestSoftwareInformation_InformationType_FIRMWARE_VERSION;


const pb_field_t requestSoftwareInformation_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, requestSoftwareInformation, information, information, &requestSoftwareInformation_information_default),
    PB_LAST_FIELD
};

const pb_field_t firmwareVersion_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, firmwareVersion, major, major, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, firmwareVersion, minor, major, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, firmwareVersion, patch, minor, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, firmwareVersion, hotfix, patch, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
