/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Sun Aug  5 17:39:22 2018. */

#include "batteryState.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t batteryState_fields[2] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, batteryState, voltage, voltage, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
