/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Wed Aug 22 07:50:30 2018. */

#ifndef PB_BATTERYSTATE_PB_H_INCLUDED
#define PB_BATTERYSTATE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _batteryState_StateType {
    batteryState_StateType_UNDEFINED = 0,
    batteryState_StateType_OK = 1,
    batteryState_StateType_WARNING = 2,
    batteryState_StateType_STOP = 3,
    batteryState_StateType_SHUTDOWN = 4
} batteryState_StateType;
#define _batteryState_StateType_MIN batteryState_StateType_UNDEFINED
#define _batteryState_StateType_MAX batteryState_StateType_SHUTDOWN
#define _batteryState_StateType_ARRAYSIZE ((batteryState_StateType)(batteryState_StateType_SHUTDOWN+1))

/* Struct definitions */
typedef struct _batteryState {
    batteryState_StateType state;
    float voltage;
/* @@protoc_insertion_point(struct:batteryState) */
} batteryState;

/* Default values for struct fields */
extern const batteryState_StateType batteryState_state_default;

/* Initializer values for message structs */
#define batteryState_init_default                {batteryState_StateType_UNDEFINED, 0}
#define batteryState_init_zero                   {_batteryState_StateType_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define batteryState_state_tag                   1
#define batteryState_voltage_tag                 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t batteryState_fields[3];

/* Maximum encoded size of messages (where known) */
#define batteryState_size                        7

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BATTERYSTATE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
