/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Wed Aug 22 07:50:30 2018. */

#include "batteryState.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const batteryState_StateType batteryState_state_default = batteryState_StateType_UNDEFINED;


const pb_field_t batteryState_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, batteryState, state, state, &batteryState_state_default),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, batteryState, voltage, state, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
