/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Sun Jul 22 14:52:20 2018. */

#include "dust.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t dustMessage_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dustMessage, dustPercentage, dustPercentage, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
