/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Wed Aug 22 08:54:06 2018. */

#ifndef PB_PROTOBUF_NODESTATUS_PB_H_INCLUDED
#define PB_PROTOBUF_NODESTATUS_PB_H_INCLUDED
#include <pb.h>

#include "dustMeasurement.pb.h"

#include "applicationInformation.pb.h"

#include "batteryState.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _protobuf_NodeMessage_InformationType {
    protobuf_NodeMessage_InformationType_UNDEFINED_MESSAGE = 0,
    protobuf_NodeMessage_InformationType_APPLICATION_INFO = 1,
    protobuf_NodeMessage_InformationType_BATTERY_STATE = 2,
    protobuf_NodeMessage_InformationType_DUST_MEASUREMENT = 3
} protobuf_NodeMessage_InformationType;
#define _protobuf_NodeMessage_InformationType_MIN protobuf_NodeMessage_InformationType_UNDEFINED_MESSAGE
#define _protobuf_NodeMessage_InformationType_MAX protobuf_NodeMessage_InformationType_DUST_MEASUREMENT
#define _protobuf_NodeMessage_InformationType_ARRAYSIZE ((protobuf_NodeMessage_InformationType)(protobuf_NodeMessage_InformationType_DUST_MEASUREMENT+1))

/* Struct definitions */
typedef struct _protobuf_NodeMessage {
    protobuf_NodeMessage_InformationType information;
    pb_size_t which_msg;
    union {
        protobuf_firmwareVersion appInfoData;
        protobuf_dustSensorMeasurement dustMeasurementData;
        protobuf_batteryState batteryStateData;
    } msg;
/* @@protoc_insertion_point(struct:protobuf_NodeMessage) */
} protobuf_NodeMessage;

/* Default values for struct fields */
extern const protobuf_NodeMessage_InformationType protobuf_NodeMessage_information_default;

/* Initializer values for message structs */
#define protobuf_NodeMessage_init_default        {protobuf_NodeMessage_InformationType_UNDEFINED_MESSAGE, 0, {protobuf_firmwareVersion_init_default}}
#define protobuf_NodeMessage_init_zero           {_protobuf_NodeMessage_InformationType_MIN, 0, {protobuf_firmwareVersion_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define protobuf_NodeMessage_appInfoData_tag     2
#define protobuf_NodeMessage_dustMeasurementData_tag 3
#define protobuf_NodeMessage_batteryStateData_tag 4
#define protobuf_NodeMessage_information_tag     1

/* Struct field encoding specification for nanopb */
extern const pb_field_t protobuf_NodeMessage_fields[5];

/* Maximum encoded size of messages (where known) */
#define protobuf_NodeMessage_size                28

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define NODESTATUS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
