/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Wed Aug 22 08:54:06 2018. */

#include "nodeStatus.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const protobuf_NodeMessage_InformationType protobuf_NodeMessage_information_default = protobuf_NodeMessage_InformationType_UNDEFINED_MESSAGE;


const pb_field_t protobuf_NodeMessage_fields[5] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, protobuf_NodeMessage, information, information, &protobuf_NodeMessage_information_default),
    PB_ONEOF_FIELD(msg,   2, MESSAGE , ONEOF, STATIC  , OTHER, protobuf_NodeMessage, appInfoData, information, &protobuf_firmwareVersion_fields),
    PB_ONEOF_FIELD(msg,   3, MESSAGE , ONEOF, STATIC  , UNION, protobuf_NodeMessage, dustMeasurementData, information, &protobuf_dustSensorMeasurement_fields),
    PB_ONEOF_FIELD(msg,   4, MESSAGE , ONEOF, STATIC  , UNION, protobuf_NodeMessage, batteryStateData, information, &protobuf_batteryState_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(protobuf_NodeMessage, msg.appInfoData) < 65536 && pb_membersize(protobuf_NodeMessage, msg.dustMeasurementData) < 65536 && pb_membersize(protobuf_NodeMessage, msg.batteryStateData) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_protobuf_NodeMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(protobuf_NodeMessage, msg.appInfoData) < 256 && pb_membersize(protobuf_NodeMessage, msg.dustMeasurementData) < 256 && pb_membersize(protobuf_NodeMessage, msg.batteryStateData) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_protobuf_NodeMessage)
#endif


/* @@protoc_insertion_point(eof) */
